version: "3.7"
services:
  # react app
  portfolio:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: portfolio
    volumes:
      - './:/app'
    ports:
      - '3000:3000'
    command: npm run start