version: '3.7'
services:
  node_install:
    image: node:20.8.1-alpine3.18
    container_name: node_install_portfolio
    volumes:
      - ./:/home/node/
    user: 1000:1000
    working_dir: /home/node/
    command: npm i
  
  node_run:
    image: node:20.8.1-alpine3.18
    container_name: node_run_portfolio
    volumes:
      - ./:/home/node/
    user: 1000:1000
    working_dir: /home/node/
    command: npm run start
    ports:
      - "3000:3000"
    depends_on:
      node_install:
        condition: service_completed_successfully
